name: "Build ffmpeg"

on:
  push:
  workflow_dispatch:
  
env:
  config: --enable-shared --toolchain=msvc
  MSYS2_PATH_TYPE: inherit
jobs:
  build:
    runs-on: windows-latest
    # defaults:
    #   run:
    #     shell: msys2 {0}
    strategy:
      matrix:
        arch: [amd64]
    steps:
      - uses: actions/checkout@v2
        with:
          repository: FFmpeg/FFmpeg
      - uses: msys2/setup-msys2@v2
        with:
          install: diffutils
      # - uses: microsoft/setup-msbuild@v1.1
      #   with:
      #     msbuild-architecture: ${{matrix.arch}}
      # - name: find msvc installation
      #   run: 
      # - uses: ilammy/setup-nasm@v1
      - name: remove link
        run: msys2 -c "rename link link2 $(which link)"
      - name: build
        shell: cmd
        run: |
          vswhere -all -legacy -property installationPath>>installationPath
          set /p installationPath=<installationPath
          echo installationPath=%installationPath%
          call "%installationPath%\VC\Auxiliary\Build\vcvarsall.bat" ${{matrix.arch}}
          msys2 -c "./configure ${{env.config}};make"
      - name: Start SSH session
        uses: luchihoratiu/debug-via-ssh@main
        if: ${{ failure() }}
        with:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
          SSH_PASS: ${{ secrets.SSH_PASS }}
          NGROK_REGION: ${{ secrets.NGROK_REGION }}