name: "Build"

on:
  push:
    tags: "*"

env:
  MSYS2_PATH_TYPE: inherit
jobs:
  build:
    strategy:
      matrix:
        arch: [x86, amd64, arm, arm64]
        type: [static, shared]
        license: [gpl, lgpl]
      fail-fast: false
    runs-on: windows-latest
    env:
      # amd64_arm,amd64_arm64,x86,amd64
      name: ffmpeg-${{ github.ref_name }}-${{matrix.license}}-${{matrix.arch}}-${{matrix.type}}
      target: ${{contains(matrix.arch,'arm')&&format('amd64_{0}',matrix.arch)||matrix.arch}}
    steps:
      - name: Find MSVC
        shell: bash
        id: msvc
        run: |
          echo "installationPath=$(vswhere -all -legacy -property installationPath)">>$GITHUB_OUTPUT
      #winget install mesonbuild.meson
      # - name: Setup Mesonbuild
      #   shell: cmd
      #   run: |
      #     python3 -m pip install meson
      #     meson -v
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: msys2/setup-msys2@v2
        with:
          install: >-
            diffutils
            make
            zip
            pkgconf
            yasm
            nasm

      - name: Remove MSYS2 link
        shell: msys2 {0}
        run: rm $(which link)

      - name: Build
        shell: cmd
        run: |
          CALL "${{steps.msvc.outputs.installationPath}}\VC\Auxiliary\Build\vcvarsall.bat" ${{env.target}}
          msys2 -c "./build.sh ${{matrix.arch}} ${{matrix.type}} ${{matrix.license}}"
      - name: Debug log
        if: ${{ failure() }}
        shell: bash
        run: |
          echo [Debug]
          cat FFmpeg/ffbuild/config.log
          cat FFmpeg/ffbuild/config.mak
          cat FFmpeg/config.h
      - name: Pack
        shell: msys2 {0}
        run: |
          cd dist
          zip -9 ../${{env.name}}.zip -r .
          tar -czf ../${{env.name}}.tar.gz .
          cd ..
          sha1sum ${{env.name}}.zip ${{env.name}}.tar.gz >${{env.name}}.sha1
          ./build-changelog.sh > changelog
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          body_path: changelog
          files: |
            ${{env.name}}.zip
            ${{env.name}}.tar.gz
            ${{env.name}}.sha1
