name: "Build ffmpeg"

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

  
env:
  config: --enable-shared --toolchain=msvc
  MSYS2_PATH_TYPE: inherit
jobs:
  check:
    runs-on: windows-latest
    outputs:
      build: ${{github.ref_name}} != ${{steps.ffmpeg.outputs.tag}}
    steps:
      - name: Check tag
        shell: bash
        id: ffmpeg
        run: |
          git clone https://github.com/FFmpeg/FFmpeg.git ffmpeg --depth 5000 
          cd ffmpeg
          echo "::set-output name=tag::$(git describe --tags --abbrev=0)"
          echo "VER=$(git describe --tags --abbrev=0)"
      - uses: actions/checkout@v2
        if: ${{github.ref_name}} != ${{steps.ffmpeg.outputs.tag}}
        with:
          path: repository
      - name: update
        shell: bash
        if: ${{github.ref_name}} != ${{steps.ffmpeg.outputs.tag}}
        run: |
          cd repository
          echo ${{steps.ffmpeg.outputs.tag}} > ffmpeg-latest
          git config --global user.name "$(git log --format='%an' HEAD^!)"
          git config --global user.email "$(git log --format='%ae' HEAD^!)"
          git add .
          git commit -m ${{steps.ffmpeg.outputs.tag}}
          git tag ${{steps.ffmpeg.outputs.tag}}
          git push origin ${{steps.ffmpeg.outputs.tag}}
  build:
    needs: check
    if: ${{needs.check.outputs.build}}
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x86,amd64]
    steps:
      - uses: actions/checkout@v2
        with:
          repository: FFmpeg/FFmpeg
          fetch-depth: 2000
      - uses: msys2/setup-msys2@v2
        with:
          install: >-
            diffutils
            make
            zip
      - uses: ilammy/setup-nasm@v1
      - name: remove link
        run: msys2 -c "rename link link2 $(which link)"
      - name: build
        shell: cmd
        run: |
          vswhere -all -legacy -property installationPath>>installationPath
          set /p installationPath=<installationPath
          echo installationPath=%installationPath%
          call "%installationPath%\VC\Auxiliary\Build\vcvarsall.bat" ${{matrix.arch}}
          msys2 -c "./configure ${{env.config}} --arch=${{matrix.arch}};make -j$(nproc);make install prefix=dist"
          # mkdir dist
          # echo test>dist/test.txt
      - name: pack
        shell: msys2 {0}
        run: |
          ZIP_PATH=ffmpeg-$(git describe --tags --always).zip
          echo ZIP_PATH=$ZIP_PATH>>$GITHUB_ENV
          echo ${{env.ZIP_PATH}}
          cd dist
          zip -9 ../$ZIP_PATH -r .
          cd ..
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{env.ZIP_PATH}}
      # - name: Start SSH session
      #   uses: luchihoratiu/debug-via-ssh@main
      #   if: ${{ failure() }}
      #   with:
      #     NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      #     SSH_PASS: ${{ secrets.SSH_PASS }}
      #     NGROK_REGION: ${{ secrets.NGROK_REGION }}