name: "Build FFmpeg"

on:
  workflow_dispatch:
  push:

env:
  MSYS2_PATH_TYPE: inherit
jobs:
  build:
    strategy:
      matrix:
        host: [amd64]
        arch: [x86, amd64, arm, arm64]
        type: [static, shared]
        license: [gpl, lgpl]
      fail-fast: false
    runs-on: windows-latest
    env:
      # amd64_arm,amd64_arm64,x86,amd64
      target: ${{contains(matrix.arch,'arm')&&format('{0}_{1}',matrix.host,matrix.arch)||matrix.arch}}
    steps:
      - name: Find MSVC
        shell: bash
        id: msvc
        run: |
          echo "installationPath=$(vswhere -all -legacy -property installationPath)">>$GITHUB_OUTPUT
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: msys2/setup-msys2@v2
        with:
          install: >-
            diffutils
            make
            zip
            pkgconf
            yasm
            nasm

      - name: Remove MSYS2 link
        shell: msys2 {0}
        run: rm $(which link)

      #winget install mesonbuild.meson
      - name: Setup
        shell: cmd
        run: |
          python3 -m pip install meson
      - name: Build
        shell: cmd
        run: |
          CALL "${{steps.msvc.outputs.installationPath}}\VC\Auxiliary\Build\vcvarsall.bat" ${{env.target}}
          SET ARCH=${{matrix.arch}}
          msys2 -c "./build.sh"
        env:
          config: ${{env.config}} --enable-${{matrix.type}} ${{matrix.license=='gpl'&&'--enable-gpl --enable-version3'||''}} ${{contains(matrix.arch,'arm')&&'--enable-cross-compile --disable-asm'||''}}
      - name: Debug log
        if: ${{ failure() }}
        shell: bash
        run: |
          cat ffbuild/config.log
