name: "Build ffmpeg"

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

  
env:
  config: --enable-shared --toolchain=msvc
  MSYS2_PATH_TYPE: inherit
jobs:
  build:
    strategy:
      matrix:
        arch: [amd64]
    runs-on: windows-latest
    steps:
      - name: Checkout ffmpeg
        id: ffmpeg
        run: |
          git clone https://github.com/FFmpeg/FFmpeg.git . --depth 5000 
          echo "::set-output name=tag::$(git describe --tags --abbrev=0)"
          echo "::set-output name=name::$(git describe --tags)"
          echo "::set-output name=zip::ffmpeg-$(git describe --tags)-${{matrix.arch}}.zip"
      - uses: msys2/setup-msys2@v2
        with:
          install: >-
            diffutils
            make
            zip
      - uses: ilammy/setup-nasm@v1
      - name: Remove link
        shell: msys2
        run: rm $(which link)
      - name: Setup MSVC
        shell: bash
        id: msvc
        run: |
          echo "::set-output name=installationPath::$(vswhere -all -legacy -property installationPath)"
      - name: Build ffmpeg
        shell: cmd
        run: |
          call "${{steps.msvc.outputs.installationPath}}\VC\Auxiliary\Build\vcvarsall.bat" ${{matrix.arch}}
          msys2 -c "./configure ${{env.config}} --arch=${{matrix.arch}};make -j$(nproc);make install prefix=dist"
      - name: Pack ZIP
        shell: msys2 {0}
        run: |
          cd dist
          zip -9 ../${{steps.ffmpeg.outputs.zip}} -r .
          cd ..
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ffmpeg-${{steps.ffmpeg.outputs.name}}-${{matrix.arch}}
          tag_name: ${{steps.ffmpeg.outputs.name}}
          files: |
            ${{steps.ffmpeg.outputs.zip}}