name: "Build ffmpeg"

on:
  push:
  workflow_dispatch:
  
env:
  config: --enable-shared --toolchain=msvc

jobs:
  build:
    runs-on: windows-latest
    # defaults:
    #   run:
    #     shell: msys2 {0}
    strategy:
      matrix:
        arch: [amd64]
    steps:
      # - uses: actions/checkout@v2
      #   with:
      #     repository: FFmpeg/FFmpeg
      # - uses: msys2/setup-msys2@v2
      #   with:
      #     install: diffutils
      # - uses: microsoft/setup-msbuild@v1.1
      #   with:
      #     msbuild-architecture: ${{matrix.arch}}
      # - name: find msvc installation
      #   run: 
      - name: setup msvc
        run: |
          $installationPath=$(vswhere -all -legacy -property installationPath)
          echo "installationPath=$installationPath" >> $GITHUB_ENV
      - name: test
        run: |
          echo installationPath=${{env.installationPath}}
      - name: build
        shell: "cmd.exe /k ${{env.installationPath}}\\VC\\Auxiliary\\Build\\vcvarsall.bat"
        run: |
          $installationPath=$(vswhere -all -legacy -property installationPath)
          %installationPath%\VC\Auxiliary\Build\vcvarsall.bat
          sh configure ${{env.config}}
          make
      # - name: Start SSH session
      #   uses: luchihoratiu/debug-via-ssh@main
      #   if: ${{ failure() }}
      #   with:
      #     NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      #     SSH_PASS: ${{ secrets.SSH_PASS }}
      #     NGROK_REGION: ${{ secrets.NGROK_REGION }}