name: "Build ffmpeg"

on:
  workflow_dispatch:
  
env:
  config: --enable-shared --toolchain=msvc

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    strategy:
      matrix:
        arch: [x64]
    steps:
      - uses: actions/checkout@v2
        with:
          repository: FFmpeg/FFmpeg
      - uses: msys2/setup-msys2@v2
        with:
          install: diffutils
      - uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: ${{matrix.arch}}
      - name: build
        run: |
          rename link link2 "$(which link.exe)"
          ./configure ${{env.config}}
          make
        