name: "Build ffmpeg"

on:
  push:
  workflow_dispatch:
  
env:
  config: --enable-shared --toolchain=msvc
  MSYS2_PATH_TYPE: inherit
jobs:
  build:
    runs-on: windows-latest
    # defaults:
    #   run:
    #     shell: msys2 {0}
    strategy:
      matrix:
        arch: [amd64]
    steps:
      - uses: actions/checkout@v2
        with:
          repository: FFmpeg/FFmpeg
      - uses: msys2/setup-msys2@v2
        with:
          install: >-
            diffutils
            make
      # - uses: ilammy/setup-nasm@v1
      - name: remove link
        run: msys2 -c "rename link link2 $(which link)"
      - name: build
        shell: cmd
        run: |
          # vswhere -all -legacy -property installationPath>>installationPath
          # set /p installationPath=<installationPath
          # echo installationPath=%installationPath%
          # call "%installationPath%\VC\Auxiliary\Build\vcvarsall.bat" ${{matrix.arch}}
          # msys2 -c "./configure ${{env.config}} --arch=${{matrix.arch}};make -j$(nproc);make install prefix=dist"
          mkdir dist
          echo test>dist/test.txt
      - name: pack
        shell: msys2
        run: |
          ZIP_PATH=ffmpeg-$(git describe --tags).zip
          echo ZIP_PATH=$ZIP_PATH>>$GITHUB_ENV
          echo ${{env.ZIP_PATH}}
          cd dist
          zip -9 ../$ZIP_PATH -r .
          cd ..
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{env.ZIP_PATH}}
      # - name: Start SSH session
      #   uses: luchihoratiu/debug-via-ssh@main
      #   if: ${{ failure() }}
      #   with:
      #     NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      #     SSH_PASS: ${{ secrets.SSH_PASS }}
      #     NGROK_REGION: ${{ secrets.NGROK_REGION }}