name: "Build FFmpeg"

on:
  workflow_dispatch:
  push:

env:
  MSYS2_PATH_TYPE: inherit
jobs:
  build:
    strategy:
      matrix:
        host: [amd64]
        arch: [x86, amd64, arm, arm64]
        type: [static, shared]
        license: [gpl, lgpl]
      fail-fast: false
    runs-on: windows-latest
    env:
      # amd64_arm,amd64_arm64,x86,amd64
      target: ${{contains(matrix.arch,'arm')&&format('{0}_{1}',matrix.host,matrix.arch)||matrix.arch}}
    steps:
      - name: Find MSVC
        shell: bash
        id: msvc
        run: |
          echo "installationPath=$(vswhere -all -legacy -property installationPath)">>$GITHUB_OUTPUT
      #winget install mesonbuild.meson
      # - name: Setup Mesonbuild
      #   shell: cmd
      #   run: |
      #     python3 -m pip install meson
      #     meson -v
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: msys2/setup-msys2@v2
        with:
          install: >-
            diffutils
            make
            zip
            pkgconf
            yasm
            nasm

      - name: Remove MSYS2 link
        shell: msys2 {0}
        run: rm $(which link)

      - name: Build
        shell: cmd
        run: |
          CALL "${{steps.msvc.outputs.installationPath}}\VC\Auxiliary\Build\vcvarsall.bat" ${{env.target}}
          msys2 -c "./build.sh ${{matrix.arch}} ${{matrix.type}} ${{matrix.license}}"
      - name: Debug log
        if: ${{ failure() }}
        shell: bash
        run: |
          echo [Debug]
          cat FFmpeg/ffbuild/config.log
          cat FFmpeg/ffbuild/config.mak
          cat FFmpeg/config.h
