name: Check for update

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: windows-latest
    steps:
      - uses: oprypin/find-latest-tag@v1
        id: ffmpeg
        with:
          repository: FFmpeg/FFmpeg
      - uses: actions/checkout@v2
        if: ${{github.ref_name}} != ${{steps.ffmpeg.outputs.tag}}
      - name: update
        if: ${{github.ref_name}} != ${{steps.ffmpeg.outputs.tag}}
        run: |
          git tag ${{steps.ffmpeg.outputs.tag}}
          git push origin ${{steps.ffmpeg.outputs.tag}}

        