name: "Check"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  check:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
      - name: Check
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git submodule update --init --depth 1 FFmpeg
          git -C FFmpeg fetch --tags
          git fetch --tags
          for tag_name in `git -C FFmpeg for-each-ref --sort=-taggerdate --format '%(refname:strip=2)' refs/tags |head -n 10`;do
            if git rev-parse "${tag_name}" >/dev/null 2>&1; then
              echo "skip '${tag_name}'"
            else
              echo "select '${tag_name}'"
              git -C FFmpeg checkout ${tag_name}
              git add FFmpeg
              
              git commit -m "${tag_name}"
              git tag ${tag_name} 

              git push origin ${tag_name}
            fi
          done
