name: Check for update

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: windows-latest
    steps:
      - name: Check tag
        shell: bash
        id: ffmpeg
        run: |
          git clone https://github.com/FFmpeg/FFmpeg.git ffmpeg --depth 10000 
          cd ffmpeg
          echo "::set-output name=tag::$(git describe --tags --abbrev=0)"
      - uses: actions/checkout@v2
        if: ${{github.ref_name}} != ${{steps.ffmpeg.outputs.tag}}
        with:
          path: repository
      - name: update
        shell: bash
        if: ${{github.ref_name}} != ${{steps.ffmpeg.outputs.tag}}
        run: |
          cd repository
          echo ${{steps.ffmpeg.outputs.tag}} > ffmpeg-latest
          git add .
          git commit -m ${{steps.ffmpeg.outputs.tag}}
          git tag ${{steps.ffmpeg.outputs.tag}}
          git push origin ${{steps.ffmpeg.outputs.tag}}

        